//      -----------------------------------------------------------------------
//      Licensed Materials - Property of IBM
//      IBM Decision Server
//      (c) Copyright IBM Corporation 1987, 2014. All Rights Reserved.
//      RuleApp: BOM Base Ruleapp
//      Date: Mon, 22 Sep 2014 18:50:16 EDT
//      Generated by: Decision Server 8.5.0.0
//
//      N O T I C E
//
//      Changes to this file will be lost if the code is regenerated.
//      Note to U.S. Government Users Restricted Rights: 
//      Use, duplication or disclosure restricted by GSA ADP Schedule 
//      Contract with IBM Corp.
//     -----------------------------------------------------------------------

package BOMBaseRuleapp;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;

import miniloan.Borrower;

public class Main {

	public static void main(String[] args) throws Exception {
		
		XOMforJavaSERunner bean = new XOMforJavaSERunner();

		miniloan.Borrower borrowerBOMBase = getSampleBorrower1();
		miniloan.Borrower coborrowerBOMBase = null;
		miniloan.Loan loanBOMBase = null;
		miniloan.RequestAppendix requestBOMBase = null;
		miniloan.Response responseBOMBase = null;
		bean.executeBOMBase(borrowerBOMBase, coborrowerBOMBase,loanBOMBase, requestBOMBase, responseBOMBase, "\\BOMBaseRuleApp\\BOMBase");

	}
	
	public static Borrower getSampleBorrower1() throws Exception {
		Borrower borrower = new Borrower();
		borrower.setCategory("Category A");
		borrower.setDateOfBirth(getDate("01/01/2014"));
		borrower.setName("Customer A");
		return borrower;
	}
	
	public static Date getDate(String ddmmyyyySlashSeparators) throws Exception {
		DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
		return dateFormat.parse(ddmmyyyySlashSeparators);
	}
	
	public static void dateOfBirthCalculationTest() throws Exception {
		
		Calendar dob = Calendar.getInstance();  
		dob.setTime(getDate("01/01/2014"));  
		Calendar today = Calendar.getInstance();  
		int age = today.get(Calendar.YEAR) - dob.get(Calendar.YEAR);  
		if (today.get(Calendar.MONTH) < dob.get(Calendar.MONTH)) {
		  age--;  
		} else if (today.get(Calendar.MONTH) == dob.get(Calendar.MONTH)
		    && today.get(Calendar.DAY_OF_MONTH) < dob.get(Calendar.DAY_OF_MONTH)) {
		  age--;  
		}
		System.out.println("age = " + age);
	}
}
