//      -----------------------------------------------------------------------
//      Licensed Materials - Property of IBM
//      IBM Decision Server
//      (c) Copyright IBM Corporation 1987, 2014. All Rights Reserved.
//      RuleApp: BOM Base Ruleapp
//      Date: Mon, 22 Sep 2014 18:50:16 EDT
//      Generated by: Decision Server 8.5.0.0
//
//      N O T I C E
//
//      Changes to this file will be lost if the code is regenerated.
//      Note to U.S. Government Users Restricted Rights: 
//      Use, duplication or disclosure restricted by GSA ADP Schedule 
//      Contract with IBM Corp.
//     -----------------------------------------------------------------------

package BOMBaseRuleapp;

public class RulesetExecutionException extends Exception {
	private static final long serialVersionUID = 1L;
	private String rulesetName;

	public RulesetExecutionException(String rulesetName) {
		this(rulesetName, "");
	}

	public RulesetExecutionException(String rulesetName, String message) {
		super(rulesetName + message);
		this.rulesetName = rulesetName;
	}

	public RulesetExecutionException(String rulesetName, String message,
			Throwable cause) {
		this(rulesetName, message + cause.getMessage());
	}

	public RulesetExecutionException(String rulesetName, Throwable cause) {
		this(rulesetName, cause.getMessage());
	}

	public String getRulesetName() {
		return rulesetName;
	}
}
